///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Assets {
  Assets._();

  static const String imagesForgotPassImage = 'assets/images/Forgot_pass_image.svg';
  static const String imagesFrame1 = 'assets/images/Frame 1.svg';
  static const String imagesFrame2 = 'assets/images/Frame 2.svg';
  static const String imagesFrame3 = 'assets/images/Frame 3.svg';
  static const String imagesSucccesordericon = 'assets/images/Succes order icon.svg';
  static const String imagesVector1 = 'assets/images/Vector 1.svg';
  static const String imagesVector2 = 'assets/images/Vector 2.svg';
  static const String imagelabel = 'assets/images/Dalel.svg';
  static const String imagesAncientEgypt = 'assets/images/ancientEgypt.png';
  static const String imagesIslamicEra = 'assets/images/islamicera.png';
}
